services:
  nginx_site1:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    networks:
      - nginx_network
    env_file:
      - .env
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-template.conf:/etc/nginx/templates/nginx-template.conf
    command:
      - sh
      - -c
      - |
        envsubst < /etc/nginx/templates/nginx-template.conf > /etc/nginx/conf.d/nginx.conf
        nginx -g 'daemon off;'
networks:
  nginx_network:
    name: my-nginx-network
    external: true