services:
  backend_django_site1:
    build: ./simple_django_project
    container_name:
      backend_django_site1
    command: gunicorn simple_django_project.wsgi:application --bind 0.0.0.0:8000
    networks:
      - nginx_network
    expose:
      - 8000

  nginx_django_site1:
    image: nginx:latest
    container_name:
      ${NGINX_CONTAINER_NAME}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx-template.conf:/etc/nginx/templates/nginx-template.conf
    #    ports:
    #      - "80:80"
    env_file:
      - .env
    networks:
      - nginx_network
    command:
      - sh
      - -c
      - |
        envsubst '$${SERVER_NAME}' < /etc/nginx/templates/nginx-template.conf > /etc/nginx/conf.d/nginx.conf
        nginx -g 'daemon off;'
    depends_on:
      - backend_django_site1

networks:
  nginx_network:
    name: my-nginx-network
    external: true