services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "9001:9001"
      - "9002:9002"
    networks:
      - nginx_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  nginx_network:
    external: true
