services:
  nginx_reverse_proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command:
      - sh
      - -c
      - |
        envsubst '$${SERVER_NAME_1} $${SERVER_NAME_2} $${SERVER_NAME_3}' < /etc/nginx/templates/nginx-template.conf > /etc/nginx/conf.d/nginx.conf
        nginx -g 'daemon off;'

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c '
      trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h;
      done
      '
  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    depends_on:
      - nginx_reverse_proxy
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c '
      certbot certonly --webroot --webroot-path=/var/www/certbot --agree-tos --no-eff-email --staging --email aligorji@hotmail.comm -d docker-deploy-test-1.algor.cc -d docker-deploy-test-2.algor.cc -d docker-deploy-test-3.algor.cc
      '