services:
  nginx_reverse_proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx-template.conf:/etc/nginx/templates/nginx-template.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    env_file:
      - .env
    networks:
      - nginx_network
    command:
      - sh
      - -c
      - |
        envsubst '$${SERVER_NAME_1} $${SERVER_NAME_2} $${SERVER_NAME_3}' < /etc/nginx/templates/nginx-template.conf > /etc/nginx/conf.d/nginx.conf
        nginx -g 'daemon off;'

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c '
      trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h;
      done
      '

networks:
  nginx_network:
    name: ${NGINX_NETWORK_NAME}
    external: true
